### ISSUE TITLE
[FIXME] Keep just one (spinner?) for location toggle, add price tag for requests 

### ISSUE THREAD

**Issue by 2DSharp** [BroadwayFriends/FriendlyNeighborAndroid#13]
Currently, there are two text fields that show your default location and radius.

 - Remove that and use a spinner that keeps the default location and radius as selected (show one line of user address as feedback to the user, not LatLng, and radius in KM). 

- On clicking "Custom", take them to the location picker, allow them to select location and radius. Use the new LatLng, Radius information for that particular request. 

- Put a text field next to the slider for allowing users to enter radius manually. (Make a decision on whether we want floating-point values)

- Show feedback to the user after returning to the activity with Maps API about the newly selected location. (Not LatLng)

- Ask for a price tag.

**Comment by ritwikbadola** [comment]
Fixed.
